
defaults:
  - _self_
  - dataset: com_momentum
  - model: emlp
  - robot: solo

# TODO: Make distinctions between. Trainer Args, Model Psecific Args, Program Args
#robot: 'solo12'
seed: -1
exp_name: 'tests'

device: 0
num_workers: 0  # Dataloader workers

debug: False
debug_loops: False
use_volatile: False

# Hydra configuration _________
hydra:
  run:
    dir: ./experiments/${hydra.job.name}/${hydra.job.override_dirname}

  job:
    # TODO: Reorganize output dir
    name: ${dataset.job_name}
    num: ${seed}
    env_set:
      XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
      HYDRA_FULL_ERROR: '1'
    config:
      override_dirname:
        kv_sep: "="
        item_sep: " "
        exclude_keys:
          - batch_size
          - model
          - model.model_type
          - model.num_channels
          - model.num_layers
          - model.fine_tune_num_layers
          - model.fine_tune_num_layers
          - device
          - exp_name
          - max_epochs
          - dataset.train_ratio
          - dataset.val_ratio
          - dataset.test_ratio
          - run_type
          - kfolds
          - dataset
          - debug
          - debug_loops
          - seed
          - use_volatile

  sweep:
    dir: ./experiments/${hydra.job.name}/
    subdir: ${hydra.job.override_dirname}

  job_logging:
    version: 1
    colorlog: True
    formatters:
      simple:
        format: '[%(levelname)s][%(name)s] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: log.log
        maxBytes: 2048
        backupCount: 1
    root:
      handlers: [console]

    disable_existing_loggers: false