#
job_name: ${exp_name}_${robot.name}/model=${model.model_type}_train_ratio=${dataset.train_ratio}_ly=${model.num_layers}_hc=${model.num_channels}

name: 'com_momentum'

data_folder: "dataset/com_momentum"

augment: False
angular_momentum: True

kinetic_energy: False

standarize: True

batch_size: 2048
max_epochs: 200
log_every_n_epochs: 0.5

#samples: 100000     # Dataset size.
samples: 10000     # Dataset size.
train_ratio: 0.7
