
job_name: ${exp_name}_${robot.name}/model=${model.model_type}_train_ratio=${dataset.train_ratio}
name: "contact"

data_folder: "training_splitted"

contact_type: "contact"

log_every_n_epochs: 0.15   # 4 times per epoch

augment: false
balanced_classes: false # Use class frequencies to weight cross entropy loss
max_epochs: 60
batch_size: 30
window_size: 150

# Dataset is already partitioned in training-val data and test data separatedly
# this is why we use 15 % of the train-val data for validation the rest for training
# and why the ratio for testing is set to 1, to use all of the test data
train_ratio: 0.85
test_ratio: 1
val_ratio: 0.15

shuffle: True


