
defaults:
  - _self_
  - dataset: com_momentum
  - model: emlp

# TODO: Make distinctions between. Trainer Args, Model Psecific Args, Program Args
robot_name: 'bolt'
#init_mode: 'fan_in'   # Forward constant activation variance or cnst gradient backward variance.

#model_type: 'emlp'
#bias: false
#lr: 1e-3
#lr_trials: 50
#num_layers: 1
#num_channels: 64
seed: -1
#batch_size: 512

exp_name: 'tests'

device: 0
#max_epochs: 2

# Run parameters
run_type: single_run
kfolds: 5

# Hydra configuration _________
hydra:
  run:
    dir: ./experiments/${hydra.job.name}/${hydra.job.override_dirname}

  job:
    # TODO: Reorganize output dir
    name: ${dataset.job_name}
    num: ${seed}
    env_set:
      XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
      HYDRA_FULL_ERROR: '1'
    config:
      override_dirname:
        kv_sep: "="
        item_sep: " "
        exclude_keys:
          - batch_size
          - model_type
          - num_channels
          - num_layers
          - device
          - robot_name
          - exp_name
          - max_epochs
          - dataset.train_samples
          - dataset.val_samples
          - dataset.test_samples
          - run_type
          - kfolds
          - dataset
          - seed

  sweep:
    dir: ./experiments/${hydra.job.name}/
    subdir: ${hydra.job.override_dirname}

  job_logging:
    version: 1
    colorlog: True
    formatters:
      simple:
        format: '[%(levelname)s][%(name)s] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: log.log
        maxBytes: 2048
        backupCount: 1
    root:
      handlers: [console]

    disable_existing_loggers: false