#
job_name: ${exp_name}_${robot_name}/model=${model.model_type}_train_ratio=${dataset.train_ratio}
name: "contact"

data_folder: "training_splitted"

contact_type: "contact"

log_every_n_epochs: 0.15   # 4 times per epoch

augment: false
balanced_classes: false # Use class frequencies to weight cross entropy loss
max_epochs: 60
batch_size: 30
window_size: 150


train_ratio: 0.7
test_ratio: 0.15
val_ratio: 0.15

shuffle: True


